//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductIngredient
    {
        public int ProductIngredientId { get; set; }
        public int ProductId { get; set; }
        public int IngredientId { get; set; }
        public int Quantity { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Product Product { get; set; }
    }
}
